name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install uv and python
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        python-version: ${{ matrix.python-version }}

    - name: Install depenencies ${{ matrix.python-version }}
      run: make init

    - name: Run linting
      run: make lint

    - name: Run tests
      run: make test
